### ISSUE TITLE
Change normal html input form

### ISSUE THREAD

**Issue by Shivam010** [Shivam010/populateG#3]
The application uses the static normal HTML input form. Change it or use some CSS

**Comment by CamiloGarciaLaRotta** [comment]
Hi @Shivam010, neat project!

I am interested in helping around with this issue.
If its still up for grabs, would you want to chat on what your vision for the styling might be?

**Comment by Shivam010** [comment]
Hello @CamiloGarciaLaRotta 
Thanks for showing interest and yes it's still up for grab.

**Comment by Shivam010** [comment]
I don't want a heavy page, just a simple page with some introductory information and something to take in the information. Everything must look as simple as possible.

@CamiloGarciaLaRotta if you have any ideas I am open for it.

**Comment by CamiloGarciaLaRotta** [comment]
I can open a draft PR with a base proposal
My only follow up question so far is: do you prefer using a styling library like Bootstrap or [Primer](https://primer.style/). Or do you prefer using vanilla CSS?

**Comment by Shivam010** [comment]
Sure, you can use any of them, the idea is just to keep everything simple & straight. And Primer will also work for me, if you want to use it, just keep it static.

Also, right now all the pages are hard-coded in the request handlers, so I am opening an issue regarding moving them to a separate directory. 

By the time, you can start your work in a separate directory, named `pages`. I am setting up the [`dev`](https://github.com/Shivam010/populateG/tree/dev) branch for you to merge and work on.

**Comment by Shivam010** [comment]
I have set up the [`dev`](https://github.com/Shivam010/populateG/tree/dev) for you and have assigned the issue to you. 
If you have any question, feel free to ask

**Comment by SudhiMohan** [comment]
Hi.. I would like to contribute to this project as well.
I do not know much about Go. But I know HTML and CSS. Shall I create a static HTML/CSS login page?
